# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Python code lint and formatting with ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Version should be kept in sync with .pre-commit_config.yaml & also micropython
    - run: pip install --user ruff==0.11.6
    - run: ruff check --output-format=github .
    - run: ruff format --diff .
